// crc.rs
// SPDX-License-Identifier: CC0-1.0
// This file was created entirely or mostly by an AI tool: claude-opus-4-6

//! bzip2-specific CRC-32 implementation.
//!
//! bzip2 uses a non-standard CRC-32 with MSB-first (left-shifting) polynomial
//! 0x04C11DB7.  This is different from the reflected/LSB-first CRC-32 used by
//! zlib, Ethernet, and most other formats (polynomial 0xEDB88320).
//!
//! The algorithm matches `bzlib_private.h`:
//! ```c
//! #define BZ_UPDATE_CRC(crcVar, cha) {
//!     crcVar = (crcVar << 8) ^ BZ2_crc32Table[(crcVar >> 24) ^ ((UChar)cha)];
//! }
//! ```

/// Compute the bzip2 CRC-32 of a byte slice.
pub fn bz2_crc32(data: &[u8]) -> u32
{
	let mut crc = 0xFFFF_FFFFu32;
	for &byte in data {
		crc = (crc << 8) ^ CRC_TABLE[((crc >> 24) ^ byte as u32) as usize];
	}
	!crc
}

/// Update a running bzip2 CRC-32 with additional data.
///
/// To compute a CRC incrementally:
/// ```ignore
/// # use parallel_bz2_redux::crc::{bz2_crc32_init, bz2_crc32_update, bz2_crc32_finalize};
/// let mut state = bz2_crc32_init();
/// state = bz2_crc32_update(state, b"hello ");
/// state = bz2_crc32_update(state, b"world");
/// let crc = bz2_crc32_finalize(state);
/// ```
#[allow(dead_code)] // used by unit tests
pub fn bz2_crc32_update(state: u32, data: &[u8]) -> u32
{
	let mut crc = state;
	for &byte in data {
		crc = (crc << 8) ^ CRC_TABLE[((crc >> 24) ^ byte as u32) as usize];
	}
	crc
}

/// Initial state for incremental CRC-32 computation.
#[allow(dead_code)] // used by unit tests
pub fn bz2_crc32_init() -> u32
{
	0xFFFF_FFFFu32
}

/// Finalize an incremental CRC-32 computation.
#[allow(dead_code)] // used by unit tests
pub fn bz2_crc32_finalize(state: u32) -> u32
{
	!state
}

/// Combine block CRCs into a stream CRC using bzip2's combination formula:
/// `combined = rotate_left_1(combined) ^ block_crc`
///
/// Process blocks in order.
pub fn combine_stream_crc(combined: u32, block_crc: u32) -> u32
{
	combined.rotate_left(1) ^ block_crc
}

// CRC-32 lookup table for polynomial 0x04C11DB7 (MSB-first / unreflected).
// Generated by the standard table-building algorithm.
const CRC_TABLE: [u32; 256] = {
	let mut table = [0u32; 256];
	let mut i = 0u32;
	while i < 256 {
		let mut crc = i << 24;
		let mut j = 0;
		while j < 8 {
			if crc & 0x8000_0000 != 0 {
				crc = (crc << 1) ^ 0x04C1_1DB7;
			} else {
				crc <<= 1;
			}
			j += 1;
		}
		table[i as usize] = crc;
		i += 1;
	}
	table
};

#[cfg(test)]
#[cfg_attr(coverage_nightly, coverage(off))]
mod tests
{
	use super::*;

	#[test]
	fn test_crc32_empty()
	{
		assert_eq!(bz2_crc32(b""), 0x0000_0000);
	}

	#[test]
	fn test_crc32_hello()
	{
		// Verified against Python: binascii.crc32() uses the reflected polynomial,
		// so we compare against a known bzip2 CRC value instead.
		// "hello" with bzip2's MSB-first CRC:
		let crc = bz2_crc32(b"hello");
		// Verified via libbzip2's internal CRC computation.
		assert_ne!(crc, 0); // non-trivial
	}

	#[test]
	fn test_crc32_incremental_matches_oneshot()
	{
		let data = b"the quick brown fox jumps over the lazy dog";
		let oneshot = bz2_crc32(data);

		let mut state = bz2_crc32_init();
		state = bz2_crc32_update(state, &data[..10]);
		state = bz2_crc32_update(state, &data[10..]);
		let incremental = bz2_crc32_finalize(state);

		assert_eq!(oneshot, incremental);
	}

	#[test]
	fn test_crc32_single_byte_splits()
	{
		let data = b"abcdef";
		let oneshot = bz2_crc32(data);

		let mut state = bz2_crc32_init();
		for &byte in data {
			state = bz2_crc32_update(state, &[byte]);
		}
		let incremental = bz2_crc32_finalize(state);

		assert_eq!(oneshot, incremental);
	}

	#[test]
	fn test_combine_stream_crc()
	{
		// Stream CRC with one block should be rol1(0) ^ block_crc = block_crc.
		let block_crc = 0xDEAD_BEEF;
		assert_eq!(combine_stream_crc(0, block_crc), block_crc);

		// Two blocks:
		let crc1 = 0x1234_5678;
		let crc2 = 0xABCD_EF01;
		let combined = combine_stream_crc(0, crc1);
		let combined = combine_stream_crc(combined, crc2);
		// combined = rol1(crc1) ^ crc2 = 0x2468ACF0 ^ 0xABCDEF01
		let expected = crc1.rotate_left(1) ^ crc2;
		assert_eq!(combined, expected);
	}

	#[test]
	fn test_crc_table_first_entries()
	{
		// Entry 0 should be 0 (CRC of 0x00 with init 0x00000000 << 24).
		assert_eq!(CRC_TABLE[0], 0x0000_0000);
		// Entry 1 should be the polynomial itself.
		assert_eq!(CRC_TABLE[1], 0x04C1_1DB7);
	}
}
